on:
  push:
    branches:
      - 'main'
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean compile assembly:single
      - uses: actions/upload-artifact@v2
        with:
          name: menu-server.jar
          path: ./target/menu-server.jar
